version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-central-1:156962844638:task-definition/pension-service:3"
        LoadBalancerInfo:
          ContainerName: "pension-service"
          ContainerPort: "8083"
        PlatformVersion: "LATEST"